name: msg91
description: msg91 - msg91.com Official API Wrapper (Unofficial Dart Package)
version: 1.0.2+1
repository: https://github.com/luckycreationsindia/msg91
homepage: https://github.com/luckycreationsindia/msg91
issue_tracker: https://github.com/luckycreationsindia/msg91/issues
license: "MIT"

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  http: ^1.2.2

dev_dependencies:
  lints: ^4.0.0
  test: ^1.25.8

platforms:
  windows:
  linux:
  android:
  ios:
  macos:
  web: