name: msg91
description: msg91 - msg91.com Official API Wrapper (Unofficial Dart Package)
version: 1.0.0+2
repository: https://github.com/luckycreationsindia/msg91
homepage: https://github.com/luckycreationsindia/msg91
issue_tracker: https://github.com/luckycreationsindia/msg91/issues
license: "MIT"

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  http: ^1.1.0

dev_dependencies:
  lints: ^2.1.1
  test: ^1.24.6

platforms:
  windows:
  linux:
  android:
  ios:
  macos:
  web: